hide: true
title: Product
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
      -
        handle: template
        field:
          hide_partials: true
          display: Template
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          validate:
            - required
  product:
    display: Product
    fields:
      -
        handle: product_sub_title
        field:
          input_type: text
          antlers: false
          display: 'Product Sub Title'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          validate:
            - required
      -
        handle: items
        field:
          collapse: false
          sets:
            product:
              display: Product
              fields:
                -
                  import: card_w_link
                  prefix: product
          display: Items
          type: replicator
          icon: replicator
          listable: hidden
          instructions_position: above
